### ISSUE TITLE
FileNotFoundError when downloading

### ISSUE THREAD

**Issue by cmontesano** [CapitaineJSparrow/steam-repo-manager#6]
This happens in `override_default_length_library` because `library_path` is hard coded to "/home/sparrow/Desktop/library.js" in `utils/__init__.py`

```python
Traceback (most recent call last):
  File "/home/cmontesano/projects/steam-repo-manager/ui/widgets/library_row.py", line 16, in on_video_dl
    download_video(_, url)
  File "/home/cmontesano/projects/steam-repo-manager/utils/__init__.py", line 38, in download_video
    override_default_length_library()
  File "/home/cmontesano/projects/steam-repo-manager/utils/__init__.py", line 11, in override_default_length_library
    with open(library_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/sparrow/Desktop/library.js'
```

**Comment by CapitaineJSparrow** [comment]
It's a mistake ! It has been fixed here : https://github.com/CapitaineJSparrow/steam-repo-manager/commit/46b79794671aaf9517caf83dd53d546262989755
